name: base
channels:
  - defaults
dependencies:
  - python=3.10
  - conda==22.11.1
  - pandas==1.5.2
  - pip
  - pip:
    - nbgitpuller==2.4.3
    - openbb==2.5.*
    - quantstats==0.0.62
    - watermark==2.4.3